version: 2
sources:
- name: #REPLACEME# #PARTNER_facebook_marketing_cta
  database: #REPLACEME# #CTA-PROD-GOOGLE-PROJECT-ID
  schema: #REPLACEME# #PARTNER_facebook_marketing_cta
  tables:
  - name: _airbyte_raw_activities
  - name: _airbyte_raw_ad_account
  - name: _airbyte_raw_ad_creatives
  - name: _airbyte_raw_ad_sets
  - name: _airbyte_raw_ads
  - name: _airbyte_raw_ads_insights
  - name: _airbyte_raw_ads_insights_action_type
  - name: _airbyte_raw_campaigns
  - name: _airbyte_raw_images
  - name: _airbyte_raw_videos
  - name: ads_insights_base
  - name: ads_base
  - name: ad_creatives_base
  - name: ad_sets_base
  - name: ad_account_base
  - name: campaigns_base
  - name: account_report_agg
  - name: campaign_report_agg
  - name: ad_set_report_agg